wandb_version: 1

_wandb:
  desc: null
  value:
    bounding_box/class_labels:
      BoundingBoxDebugger_wandb_delimeter_predictions:
        key: BoundingBoxDebugger_wandb_delimeter_predictions
        type: bounding_box/class_labels
        value:
          '0': gaji-gui
          '1': galbi-gui
          '10': godeungeo-gui
          '11': gorgonzola-pizza
          '12': gochu-jangajji
          '13': ojingeochae-muchim
          '14': gopchang-jeongol
          '15': gunmandu
          '16': gimbap
          '17': kimchi-bokkeumbap
          '18': kimchi-jjigae
          '19': kkakdugi
          '2': galbi-jjim
          '20': naengmyeon
          '21': dakgalbi
          '22': dakjjim
          '23': doenjang-jjigae
          '24': dubu-gimchi
          '25': tteokgalbi
          '26': tteokguk
          '27': tteokbokki
          '28': ramyeon
          '29': maneul-jangajji
          '3': gamja-bokkeum
          '30': margherita-pizza
          '31': mandu-guk
          '32': modeum-twigim
          '33': miyeokguk
          '34': baechu-kimchi
          '35': bo-ssam
          '36': budae-jjigae
          '37': bulgogi
          '38': bibim-guksu
          '39': bibim-naengmyeon
          '4': gamja-twigim
          '40': bibimbap
          '41': samgyeopsal-gui
          '42': samgyetang
          '43': saeu-bokkeumbap
          '44': saeu-twigim
          '45': saengseonjeon
          '46': soseji-bokkeum
          '47': songpyeon
          '48': sukjunamul
          '49': sundae
          '5': geon-saewoo-bokkeum
          '50': sigumchi-namul
          '51': al-bap
          '52': aehobak-bokkeum
          '53': yangnyeom-chicken
          '54': omeu-raiseu
          '55': udong
          '56': yubuchobap
          '57': yukhoe
          '58': japgokbap
          '59': japchae
          '6': gejang
          '60': jangeogui
          '61': jangjorim
          '62': dwaejigogi-bokkeum
          '63': jokbal
          '64': gimgaru-jumeokbap
          '65': jjajangmyeon
          '66': jjamppong
          '67': jjokgalbigui
          '68': jjukkumi-bokkeum
          '69': jjinmandu
          '7': gyeongdan
          '70': cheese-pizza
          '71': curry-rice
          '72': combination-pizza
          '73': kongguksu
          '74': pajeon
          '75': hangwa
          '76': haemuljjim
          '77': haejangguk
          '78': hoe-muchim
          '79': huraideu-chicken
          '8': gyeran-mari
          '80': hunjeori
          '81': huin-juk
          '9': gyeranhurai
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1646188887
    t:
      1:
      - 1
      3:
      - 13
      - 16
      4: 3.8.10
      5: 0.12.10
      8:
      - 5
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 8
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: ''
cos_lr:
  desc: null
  value: false
data:
  desc: null
  value: /mnt/ysy/yolov5/data/kfood.yaml
data_dict:
  desc: null
  value:
    names:
    - gaji-gui
    - galbi-gui
    - galbi-jjim
    - gamja-bokkeum
    - gamja-twigim
    - geon-saewoo-bokkeum
    - gejang
    - gyeongdan
    - gyeran-mari
    - gyeranhurai
    - godeungeo-gui
    - gorgonzola-pizza
    - gochu-jangajji
    - ojingeochae-muchim
    - gopchang-jeongol
    - gunmandu
    - gimbap
    - kimchi-bokkeumbap
    - kimchi-jjigae
    - kkakdugi
    - naengmyeon
    - dakgalbi
    - dakjjim
    - doenjang-jjigae
    - dubu-gimchi
    - tteokgalbi
    - tteokguk
    - tteokbokki
    - ramyeon
    - maneul-jangajji
    - margherita-pizza
    - mandu-guk
    - modeum-twigim
    - miyeokguk
    - baechu-kimchi
    - bo-ssam
    - budae-jjigae
    - bulgogi
    - bibim-guksu
    - bibim-naengmyeon
    - bibimbap
    - samgyeopsal-gui
    - samgyetang
    - saeu-bokkeumbap
    - saeu-twigim
    - saengseonjeon
    - soseji-bokkeum
    - songpyeon
    - sukjunamul
    - sundae
    - sigumchi-namul
    - al-bap
    - aehobak-bokkeum
    - yangnyeom-chicken
    - omeu-raiseu
    - udong
    - yubuchobap
    - yukhoe
    - japgokbap
    - japchae
    - jangeogui
    - jangjorim
    - dwaejigogi-bokkeum
    - jokbal
    - gimgaru-jumeokbap
    - jjajangmyeon
    - jjamppong
    - jjokgalbigui
    - jjukkumi-bokkeum
    - jjinmandu
    - cheese-pizza
    - curry-rice
    - combination-pizza
    - kongguksu
    - pajeon
    - hangwa
    - haemuljjim
    - haejangguk
    - hoe-muchim
    - huraideu-chicken
    - hunjeori
    - huin-juk
    nc: 82
    path: ../datasets/kfood
    test: null
    train: /mnt/ysy/datasets/kfood/images/train
    val: /mnt/ysy/datasets/kfood/images/val
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 20
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value:
  - 0
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.01
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 640
label_smoothing:
  desc: null
  value: 0.0
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: batch_8_0.01_epoch_20_v5x6
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
optimizer:
  desc: null
  value: SGD
patience:
  desc: null
  value: 100
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/batch_8_0.01_epoch_20_v5x6
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: yolov5x6.pt
workers:
  desc: null
  value: 8
